import { NextResponse } from "next/server";
import { isAuthenticated } from "@/lib/auth";
import { executeAiCompletion } from "@/lib/aiClient";

export async function POST(req: Request) {
  if (!(await isAuthenticated())) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const {
      topic,
      customPrompt,
      targetKeywords,
      researchBrief,
      category: requestedCategory,
    } = await req.json();

    const subject = topic || customPrompt;
    if (!subject) {
      return NextResponse.json(
        { error: "A topic or custom prompt is required." },
        { status: 400 }
      );
    }

    const prompt = `You are a Principal Technical Writer and Senior SEO Architect for Vortix Tech (an agency building production Web Apps, Mobile Apps, n8n Automations, and AI LLM solutions).

TASK: Write an authoritative, engaging, deeply informative, and 100% SEO-optimized article on:
TITLE/SUBJECT: "${subject}"
${requestedCategory ? `CATEGORY: "${requestedCategory}"` : ""}
${targetKeywords ? `TARGET SEO KEYWORDS TO WEAVE NATURALLY: "${Array.isArray(targetKeywords) ? targetKeywords.join(", ") : targetKeywords}"` : ""}
${customPrompt ? `SPECIFIC USER INSTRUCTIONS: "${customPrompt}"` : ""}
${researchBrief ? `RESEARCH BRIEF & SOURCES TO UTILIZE: """${typeof researchBrief === "string" ? researchBrief : JSON.stringify(researchBrief)}"""` : ""}

REQUIREMENTS:
1. Provide a click-worthy, search-optimized H1 title at the top: "# Title".
2. Provide a 1-2 sentence meta description/excerpt wrapped in <excerpt>...</excerpt> (under 160 characters).
3. Provide a relevant category wrapped in <category>...</category> (e.g. "AI & Automation", "Web Development", "Case Studies", "Workflow Architecture").
4. Provide 4-8 target SEO keywords separated by commas wrapped in <keywords>...</keywords>.
5. Provide a 3-part image prompt suggestion for free image tools (Pollinations, Ideogram, Leonardo) wrapped in <image_prompt>...</image_prompt>.
6. Content structure:
   - Engaging introduction addressing the core reader pain point.
   - 3-5 comprehensive sections with clear H2 and H3 subheadings.
   - Concrete technical explanations, best practices, code snippets or architectural workflows where relevant.
   - Bullet points for scannability.
   - A dedicated "Key Takeaways" or "Next Steps" section.
   - Include real references/sources in a dedicated "References & Further Reading" section at the end if applicable.
7. Return ONLY the markdown content. Do NOT wrap the entire response in \`\`\`markdown backticks.`;

    const aiResult = await executeAiCompletion({
      prompt,
      temperature: 0.7,
      maxTokens: 3500,
    });

    const rawMarkdown = aiResult.text;

    if (!rawMarkdown) throw new Error("No content generated by the AI model");

    // Extract structured tags
    const excerptMatch = rawMarkdown.match(/<excerpt>([\s\S]*?)<\/excerpt>/i);
    const categoryMatch = rawMarkdown.match(/<category>([\s\S]*?)<\/category>/i);
    const keywordsMatch = rawMarkdown.match(/<keywords>([\s\S]*?)<\/keywords>/i);
    const imagePromptMatch = rawMarkdown.match(/<image_prompt>([\s\S]*?)<\/image_prompt>/i);
    const titleMatch = rawMarkdown.match(/^#\s+(.*)/m);

    const excerpt = excerptMatch ? excerptMatch[1].trim() : "An insightful guide by the engineering team at Vortix Tech.";
    const category = categoryMatch ? categoryMatch[1].trim() : (requestedCategory || "Technology");
    const title = titleMatch ? titleMatch[1].trim() : subject;
    const keywords = keywordsMatch
      ? keywordsMatch[1].split(",").map((k: string) => k.trim()).filter(Boolean)
      : [];
    const imagePrompt = imagePromptMatch
      ? imagePromptMatch[1].trim()
      : `${title} modern technology abstract high quality 4k digital art`;

    // Clean up internal XML tags from the markdown content
    let cleanMarkdown = rawMarkdown
      .replace(/<excerpt>[\s\S]*?<\/excerpt>/gi, "")
      .replace(/<category>[\s\S]*?<\/category>/gi, "")
      .replace(/<keywords>[\s\S]*?<\/keywords>/gi, "")
      .replace(/<image_prompt>[\s\S]*?<\/image_prompt>/gi, "")
      .trim();

    // Ensure leading # Title isn't duplicated in content if displayed separately in editor
    const wordCount = cleanMarkdown.split(/\s+/).length;
    const readTime = `${Math.max(3, Math.ceil(wordCount / 200))} min read`;

    return NextResponse.json({
      success: true,
      article: {
        title,
        excerpt,
        category,
        content: cleanMarkdown,
        keywords,
        imagePrompt,
        readTime,
      },
    });
  } catch (error) {
    return NextResponse.json(
      {
        error: "Failed to generate article",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
